language: python
fast_finish: true

matrix:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11
    - python: 3.12

install:
  - pip install pytest>=4.6
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest --cov=ycnbc/

after_success:
  - coveralls

branches:
  only:
    - main