{% set name = "ycnbc" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "207da19e87792bf742d2744eee2fe18169853c1b82cfe14a9a7cfb8d05f09137"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pandas >=0.24.0
    - requests >=2.23.0
    - lxml >=4.5.1
    - pip
    - python

  run:
    - pandas >=0.24.0
    - requests >=2.23.0
    - lxml >=4.5.1
    - python

test:
  imports:
    - ycnbc

about:
  home: "https://github.com/asepscareer/ycnbc"
  license: "Apache Software"
  license_family: "APACHE"
  license_file: ""
  summary: "CNBC data downloader"
  description:
  doc_url: "https://github.com/asepscareer/ycnbc"
  dev_url: "https://pypi.python.org/pypi/ycnbc"
  doc_source_url: https://github.com/asepscareer/ycnbc/blob/master/README.md


extra:
  recipe-maintainers:
    - asepscareer