{% set name = "ycnbc" %}
{% set version = "1.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "670D54B9688CC95B4776CF887CFA2E723D642A7A174B86F33B0D629868A1A39C"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - requests >=2.23.0
    - lxml >=4.5.1
    - pip
    - python

  run:
    - requests >=2.23.0
    - lxml >=4.5.1
    - python

test:
  imports:
    - ycnbc

about:
  home: "https://github.com/asepscareer/ycnbc"
  license: "Apache Software License"
  license_family: "APACHE"
  license_file: ""
  summary: "CNBC data downloader"
  description: "A Python package for downloading CNBC data."
  doc_url: "https://github.com/asepscareer/ycnbc"
  dev_url: "https://pypi.python.org/pypi/ycnbc"
  doc_source_url: "https://github.com/asepscareer/ycnbc/blob/master/README.md"

extra:
  recipe-maintainers:
    - asepscareer